name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ rnd_nw9DdZWlIhGc9zLRmTSwWCXHCgaQ }}
          RENDER_SERVICE_ID: ${{ srv-d6q5em95pdvs73bnlfg0 }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${srv-d6q5em95pdvs73bnlfg0}" \
               -H "Authorization: Bearer ${rnd_nw9DdZWlIhGc9zLRmTSwWCXHCgaQ}"